[build]
  command = "npm run build"
  publish = "frontend"
  functions = "netlify/functions/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."archive-students"]
  schedule = "0 0 * * *"
